# Generated by Django 4.1 on 2022-09-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
