# Generated by Django 4.1 on 2022-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_article_updated_at_chapter_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="index",
            field=models.IntegerField(default=1),
        ),
    ]
